services:
  backend:
    build:
      context: ./backend
    container_name: tier_backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres

  frontend:
    build:
      context: ./frontend
    container_name: tier_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

  db:
    image: postgres:14
    container_name: tier_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

